# Generated by Django 3.1.1 on 2020-10-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppsmeds',
            name='supp_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
