# Generated by Django 3.1.1 on 2020-10-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
