# Generated by Django 3.1.1 on 2020-10-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_suppsmeds_supp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppsmeds',
            name='supp_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
