# docker-compose.yml
version: '3'

services:
 app:
   build: .
   image: gcr.io/barn-management-290023/bm-back:latest
   ports:
     # Service will be accessible on the host at port 9090.
     - "9090:${PORT:-8080}"
   environment:
     # /run/docs/reference/container-contract
     PORT: ${PORT:-8080}
     K_SERVICE: bm-back 
     K_CONFIGURATION: bm-back 
